[package]
name = "solabi"
version = "0.0.1"
edition = "2021"
description = "Solidity ABI implementation in Rust"
license = "MIT OR Apache-2.0"

[dependencies]
ethnum = "1"
hex = "0.4"
sha3 = "0.10"

[dev-dependencies]
hex-literal = "0.3"
