[package]
name = "solabi"
version = "0.0.1"
edition = "2021"
description = "Solidity ABI implementation in Rust"
license = "MIT OR Apache-2.0"

[dependencies]
ethaddr = { version = "0.1", features = ["macros"] }
ethnum = "1"
serde = { version = "1", features = ["derive"] }
sha3 = "0.10"

[dev-dependencies]
hex-literal = "0.3"
serde_json = "1"
